### ISSUE TITLE
why this mnemonic words  generate invalid addresses

### ISSUE THREAD

**Issue by dengcg0727** [coming-chat/go-aptos#2]
I use this bip39 standard mnemonic words "heavy confirm beef vague prevent language panda scrub certain electric fix left"
to generate list of addresses and keys, but those are invalid.

APTOS,0,0x3bf2cfce46007ba84e4dbf7001719d5e55de28d53b000190aced426306eedb3e
APTOS,1,0x53f4c1177f8d13598de83cdf32d6c8715fbdc55eb58b0406bf268280d3c23f5e
APTOS,2,0x1ae491c1f64102783eec3375b7b3c378cc1b7703bc92a9be131da5743316150f
APTOS,3,0x3d2b430ced4b56ba810098bcc31e6c1be2dbd5abd75790b17cae88e766c4dbf5
APTOS,4,0x4d844c90ab79a393ca5337ea589674f04bbd9cd90bfdafbb4eb44f6ada06db14

"github.com/tyler-smith/go-bip39"

entropy, _ := bip39.NewEntropy(128)
mnemonic, _ := bip39.NewMnemonic(entropy)

seed, _ := bip39.NewSeedWithErrorChecking(mnemonic, password)
key, _ := bip32.NewMasterKey(seed)

path := []uint32{purpose, coinType, account, change, index}
	for _, n := range path {
		key, err = key.NewChildKey(n)
		if err != nil {
			fmt.Println("generate key failed", err)
			log.Fatal(err)
		}
	}

aptosAccount := aptosaccount.NewAccount(key.Key)
address := "0x" + hex.EncodeToString(aptosAccount.AuthKey[:])
privateKeyStr := fmt.Sprintf("0x%x", aptosAccount.PrivateKey[:32])
	
help me fixed it please, thanks!

**Comment by Gkirito** [comment]
> I use this bip39 standard mnemonic words "heavy confirm beef vague prevent language panda scrub certain electric fix left" to generate list of addresses and keys, but those are invalid.
> 
> APTOS,0,0x3bf2cfce46007ba84e4dbf7001719d5e55de28d53b000190aced426306eedb3e APTOS,1,0x53f4c1177f8d13598de83cdf32d6c8715fbdc55eb58b0406bf268280d3c23f5e APTOS,2,0x1ae491c1f64102783eec3375b7b3c378cc1b7703bc92a9be131da5743316150f APTOS,3,0x3d2b430ced4b56ba810098bcc31e6c1be2dbd5abd75790b17cae88e766c4dbf5 APTOS,4,0x4d844c90ab79a393ca5337ea589674f04bbd9cd90bfdafbb4eb44f6ada06db14
> 
> "github.com/tyler-smith/go-bip39"
> 
> entropy, _ := bip39.NewEntropy(128) mnemonic, _ := bip39.NewMnemonic(entropy)
> 
> seed, _ := bip39.NewSeedWithErrorChecking(mnemonic, password) key, _ := bip32.NewMasterKey(seed)
> 
> path := []uint32{purpose, coinType, account, change, index} for _, n := range path { key, err = key.NewChildKey(n) if err != nil { fmt.Println("generate key failed", err) log.Fatal(err) } }
> 
> aptosAccount := aptosaccount.NewAccount(key.Key) address := "0x" + hex.EncodeToString(aptosAccount.AuthKey[:]) privateKeyStr := fmt.Sprintf("0x%x", aptosAccount.PrivateKey[:32])
> 
> help me fixed it please, thanks!

Hi @dengcg0727 
``` go
path := []uint32{purpose, coinType, account, change, index}
``` 
Could you check your `coinType` number?
Accounding to [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md#registered-coin-types), the Aptos's coinType is `637`, hex is `0x8000027d` and it's a fixed number.

**Comment by dengcg0727** [comment]
> > I use this bip39 standard mnemonic words "heavy confirm beef vague prevent language panda scrub certain electric fix left" to generate list of addresses and keys, but those are invalid.
> > APTOS,0,0x3bf2cfce46007ba84e4dbf7001719d5e55de28d53b000190aced426306eedb3e APTOS,1,0x53f4c1177f8d13598de83cdf32d6c8715fbdc55eb58b0406bf268280d3c23f5e APTOS,2,0x1ae491c1f64102783eec3375b7b3c378cc1b7703bc92a9be131da5743316150f APTOS,3,0x3d2b430ced4b56ba810098bcc31e6c1be2dbd5abd75790b17cae88e766c4dbf5 APTOS,4,0x4d844c90ab79a393ca5337ea589674f04bbd9cd90bfdafbb4eb44f6ada06db14
> > "github.com/tyler-smith/go-bip39"
> > entropy, _ := bip39.NewEntropy(128) mnemonic, _ := bip39.NewMnemonic(entropy)
> > seed, _ := bip39.NewSeedWithErrorChecking(mnemonic, password) key, _ := bip32.NewMasterKey(seed)
> > path := []uint32{purpose, coinType, account, change, index} for _, n := range path { key, err = key.NewChildKey(n) if err != nil { fmt.Println("generate key failed", err) log.Fatal(err) } }
> > aptosAccount := aptosaccount.NewAccount(key.Key) address := "0x" + hex.EncodeToString(aptosAccount.AuthKey[:]) privateKeyStr := fmt.Sprintf("0x%x", aptosAccount.PrivateKey[:32])
> > help me fixed it please, thanks!
> 
> Hi @dengcg0727
> 
> ```go
> path := []uint32{purpose, coinType, account, change, index}
> ```
> 
> Could you check your `coinType` number? Accounding to [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md#registered-coin-types), the Aptos's coinType is `637`, hex is `0x8000027d` and it's a fixed number.

CoinTypeAPTOS CoinType = 0x8000027d

yes, I have checked.

**Comment by Gkirito** [comment]
We find the part of the derivation path code was diffident from the official typescript SDK.
Now we update this, Please check again.

I will test your case later.
And our code is based on `Petra Aptos Wallet`, its official Aptos wallet, which you can download from [github](https://github.com/aptos-labs/aptos-core/releases/tag/wallet-v0.1.10) or [Chrome Plugin](https://chrome.google.com/webstore/detail/petra-aptos-wallet/ejjladinnckdgjemekebdpeokbikhfci?hl=en-US)

And I also will use `Martain Aptos wallet` to check your issues

**Comment by dengcg0727** [comment]
thanks

finally, We find the reason:
1. new address must be active at first, you need to send a deposit transaction, then send withdraw transaction, otherwise send transaction will be display  "Invalid transaction: Type: Validation Code: SENDING_ACCOUNT_DOES_NOT_EXIST"
2. Martain Aptos wallet tips address is invalid, The reason is that they don't distinguish "inactive" and "invalid" account.
Petra Aptos Wallet is much better

In short, thank you very much

**Comment by Gkirito** [comment]
> thanks
> 
> finally, We find the reason:
> 
> 1. new address must be active at first, you need to send a deposit transaction, then send withdraw transaction, otherwise do transaction will be display  "Invalid transaction: Type: Validation Code: SENDING_ACCOUNT_DOES_NOT_EXIST"
> 2. Martain Aptos wallet tips address is invalid, The reason is that they don't distinguish "inactive" and "invalid" account.
>    Petra Aptos Wallet is much better
> 
> In short, thank you very much

Fine.
I'm glad this issue is resolved.
